name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Clone repository
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: input
    id: openshift-version
    attributes:
      label: OpenShift Version
      description: What version of OpenShift are you using?
      placeholder: "4.14.3"
    validations:
      required: true

  - type: input
    id: ansible-version
    attributes:
      label: Ansible Version
      description: What version of Ansible are you using?
      placeholder: "2.15.5"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "RHEL 9.2, macOS 14, Ubuntu 22.04"
    validations:
      required: true

  - type: dropdown
    id: container-engine
    attributes:
      label: Container Engine
      description: Which container engine are you using?
      options:
        - podman
        - docker
        - other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: Please paste any relevant error messages or logs
      render: shell
      placeholder: Paste error messages or logs here

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any additional information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the troubleshooting guide
          required: true
        - label: I have included all required information above
          required: true

