name: 📝 Documentation Issue
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation is this about?
      options:
        - README
        - User Guide
        - Developer Guide
        - Ansible Role Documentation
        - Architecture Decision Record (ADR)
        - Troubleshooting Guide
        - API/Reference Documentation
        - Tutorial
        - Other
    validations:
      required: true

  - type: input
    id: doc-location
    attributes:
      label: Documentation Location
      description: Which file or page has the issue?
      placeholder: "docs/END-USER-GUIDE.md, line 45"
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing information
        - Incorrect information
        - Outdated information
        - Typo or grammar
        - Unclear explanation
        - Broken link
        - Missing example
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the documentation issue
      placeholder: What's wrong with the documentation?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      placeholder: What would make this better?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots
      placeholder: Any additional information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help fix this?
      options:
        - label: I would be willing to submit a PR to fix this

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true

