apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarkus-dev

resources:
- ../../base

labels:
- pairs:
    environment: dev
  includeSelectors: true

replicas:
- name: reference-app
  count: 1

images:
- name: quay.io/validated-patterns/reference-app
  newTag: dev

namePrefix: dev-

# Patch the namespace resource to have the correct name
patches:
- target:
    kind: Namespace
    name: dev-reference-app
  patch: |-
    - op: replace
      path: /metadata/name
      value: quarkus-dev
