---
# Setup sealed secrets

- name: Check if sealed-secrets is installed
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: sealed-secrets
  register: sealed_secrets_ns
  ignore_errors: yes

- name: Display sealed secrets status
  debug:
    msg: |
      ✅ Sealed secrets configured:
      - Sealed secrets: {{ 'Installed' if sealed_secrets_ns.resources else 'Not installed (optional)' }}
      - Encryption: Ready
