---
# Validate secrets configuration

- name: Check if secrets namespace exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ validated_patterns_secrets_namespace }}"
  register: secrets_ns
  ignore_errors: yes

- name: Create secrets namespace if not exists
  kubernetes.core.k8s:
    name: "{{ validated_patterns_secrets_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
  when: secrets_ns.resources | length == 0

- name: Display secrets validation status
  debug:
    msg: |
      ✅ Secrets namespace validated:
      - Namespace: {{ validated_patterns_secrets_namespace }}
      - Status: Ready
