{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "quarkus-reference-app.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.rolebinding | quote }}
  labels:
    {{- include "quarkus-reference-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "quarkus-reference-app.serviceAccountName" . }}
  namespace: {{ include "quarkus-reference-app.namespace" . }}
{{- end }}
