---
# Create Gitea instance

- name: Create Gitea instance
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: pfe.rhpds.com/v1
      kind: Gitea
      metadata:
        name: "{{ gitea_instance_name }}"
        namespace: "{{ gitea_namespace }}"
      spec:
        giteaAdminUser: "{{ gitea_admin_user }}"
        giteaAdminEmail: "{{ gitea_admin_email }}"
        giteaAdminPasswordLength: 32
        giteaSsl: true
        giteaCreateUsers: true
        giteaGenerateUserFormat: "{{ gitea_user_format }}"
        giteaUserNumber: "{{ gitea_user_count }}"
        giteaUserPasswordLength: 16

- name: Wait for Gitea instance to be ready
  kubernetes.core.k8s_info:
    api_version: pfe.rhpds.com/v1
    kind: Gitea
    name: "{{ gitea_instance_name }}"
    namespace: "{{ gitea_namespace }}"
  register: gitea_instance
  until: gitea_instance.resources[0].status.adminSetupComplete | default(false)
  retries: 30
  delay: 10

- name: Extract Gitea URL
  set_fact:
    gitea_url: "{{ gitea_instance.resources[0].status.giteaRoute }}"

- name: Display instance creation status
  debug:
    msg: |
      ✅ Gitea instance created:
      - URL: {{ gitea_url }}
      - Admin user: {{ gitea_admin_user }}
