---
# Manage credentials

- name: Create RBAC for secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: secrets-manager
        namespace: "{{ validated_patterns_secrets_namespace }}"
      rules:
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["get", "list", "create", "update", "patch"]

- name: Display credential management status
  debug:
    msg: |
      ✅ Credentials managed:
      - RBAC: Configured
      - Secrets namespace: {{ validated_patterns_secrets_namespace }}
      - Ready for credential storage
