apiVersion: v1
kind: ConfigMap
metadata:
  name: reference-app-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app: reference-app
    app.kubernetes.io/name: reference-app
    app.kubernetes.io/part-of: validated-patterns
data:
  app.config: |
    # Application configuration
    app.name=reference-app
    app.version=1.0.0
    app.environment=production
