apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reference-app

labels:
- pairs:
    app: reference-app
    app.kubernetes.io/name: reference-app
    app.kubernetes.io/part-of: validated-patterns
  includeSelectors: true

resources:
# Namespace removed - ArgoCD in namespaced mode cannot manage cluster-level resources
# The namespace must be created separately before deploying the application
# - namespace.yaml
- deployment.yaml
- service.yaml
- route.yaml
- configmap.yaml
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml

images:
- name: quay.io/validated-patterns/reference-app
  newTag: latest
