apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reference-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: reference-app
    app.kubernetes.io/name: reference-app
    app.kubernetes.io/part-of: validated-patterns
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
