---
name: Docs Build

'on':
  pull_request:
    branches: ["**"]
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mkdocs.yml/requirements.txt

      - name: Build documentation
        run: |
          mkdocs build -f mkdocs.yml/mkdocs.yml --strict

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
