---
# Configure ArgoCD for pattern deployment

- name: Check if ArgoCD is installed
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: openshift-gitops
  register: argocd_ns
  failed_when: argocd_ns.resources | length == 0

- name: Create pattern namespace
  kubernetes.core.k8s:
    name: "{{ validated_patterns_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Display ArgoCD configuration status
  debug:
    msg: |
      ✅ ArgoCD configured:
      - ArgoCD namespace: openshift-gitops
      - Pattern namespace: {{ validated_patterns_namespace }}
